### ISSUE TITLE
undefined symbol: __aim_argv__

### ISSUE THREAD

**Issue by Lewis-Kang** [floodlight/infra#50]
Now, AIM_CONFIG_INCLUDE_DAEMONIZE is set to 1 while it's not defined.
It causes __aim_argv__ is used in aim_daemon.c.

However, __aim_argv__ is not defined by default. So the issue of undefined symbol: __aim_argv__

**Comment by jnealtowns** [comment]
Lewis,

You will need to rebuild all (make -B).

Jeff

**Comment by Lewis-Kang** [comment]
Jeff,

Thanks.

By default AIM_CONFIG_INCLUDE_DAEMONIZE is set to 1 and AIM_CONFIG_INCLUDE_MAIN is set to 0, so "__aim_argv__" is undefined by default. In current code, AIM users always have to set AIM_CONFIG_INCLUDE_MAIN to 1 or set AIM_CONFIG_INCLUDE_DAEMONIZE to 0 to avoid this issue, right?

/Lewis

**Comment by jnealtowns** [comment]
Lewis,

You are right. AIM_CONFIG_INCLUDE_DAEMONIZE should predicate on
AIM_CONFIG_INCLUDE_MAIN. I will fix it.

Jeff

**Comment by Lewis-Kang** [comment]
Jeff,

Thanks in advance.

Lewis

**Comment by jnealtowns** [comment]
This should resolve it.
https://github.com/floodlight/infra/commit/6376b57ff49ee65e7512a52342e59bc1f201db33

**Comment by Lewis-Kang** [comment]
Jeff,

Thanks. 

But if AIM users only define AIM_CONFIG_INCLUDE_DAEMONIZE as 1 without defining AIM_CONFIG_INCLUDE_MAIN. This issue remains. Should we blame the AIM users or modify aim_config.h as the following to avoid this case?

#if !defined(AIM_CONFIG_INCLUDE_DAEMONIZE) ||  (AIM_CONFIG_INCLUDE_DAEMONIZE == 1 && AIM_CONFIG_INCLUDE_MAIN == 0)
#define AIM_CONFIG_INCLUDE_DAEMONIZE AIM_CONFIG_INCLUDE_MAIN
#endif

**Comment by jnealtowns** [comment]
Lewis,

Apologies, the fix I put in isn't quite right. I agree we can have a
compile-time check but I'd like to look at it a little more to make sure
the permutations are correct. I'll update you when the fix is better.

J

**Comment by Lewis-Kang** [comment]
Jeff,

Any progress on this?
Thanks.

/Lewis

**Comment by jnealtowns** [comment]
Lewis,

I hope to resolve it this week.

J

**Comment by jnealtowns** [comment]
Lewis,

A consistency check to flag this problem has been added in this commit:
https://github.com/floodlight/infra/commit/6e9e78d771955e25958b8d7eaee79dd1589f256a

It also describes my suggested solution to resolve this problem, but
requires a future API change.

Let me know if have any remaining issues.

J

**Comment by jnealtowns** [comment]
This is still broken when using the onlp shared library's platform manager
code from outside the library.
We'll have to fix it properly as per my comments to resolve.

**Comment by Lewis-Kang** [comment]
Got it. Thanks
